---
title: "About me"
output: 
  html_document:
    toc: true
    toc_float: true
---

<br>

### Bio

Hi! I’m Angelica Bailey, an M.S. student in Biostatistics at Columbia University’s Mailman School of Public Health, focusing on Public Health Data Science. I completed my Bachelor's in Statistics with a minor in Computer Science at Hunter College.

<br>

### Professional Experience

<br>**NYC Department of Transportation (2025)**

Traffic Engineering & Planning Intern Summer Intern

-   Assisted with data collection process for trip generation study of NYC senior housing locations by reducing data into modes of transport.

<br>**Irvine Summer Institute in Biostatistics and Undergraduate Data Science (2024)**

Summer Program

-   Engaged in training focused on applying statistical methodologies to biomedical research, collaborating on and presenting a research project investigating the relationship between the age of onset of hypertension and the risk of dementia.

<br>**Computer Science Department of Hunter College (2023)**

Undergraduate Teaching Assistant

-   Provided individual and small-group instruction on Python to students, offering additional support to those with different learning needs, improving learning outcomes.

<br>**NYC Department of Small Business Services (2022)**

Food & Beverage Industry Partnership Summer Intern

-   Utilized Census.gov platform to assist in the creation of a variety of NYC industry-focused datasets in order to provide workforce insight to partnering businesses
